name = "kindredpaws-api"
main = "index.ts"
compatibility_date = "2026-03-31"
compatibility_flags = [ "nodejs_compat" ] 

[vars]
R2_PUBLIC_DOMAIN = "https://pub-4a41a1e2454f4e248acc76c83e.r2.dev"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "kindredpaws"
